# Generated by Django 3.0.3 on 2020-03-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountEmailaddress',
        ),
        migrations.DeleteModel(
            name='AccountEmailconfirmation',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthtokenToken',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='DjangoSite',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialaccount',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialapp',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialappSites',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialtoken',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterModelOptions(
            name='newsfeed',
            options={},
        ),
    ]
