# Generated by Django 3.0.3 on 2020-03-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200312_0915'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsfeed',
            table=None,
        ),
    ]
