# Generated by Django 3.0.3 on 2020-03-13 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200312_1737'),
        ('api', '0003_auto_20200312_1736'),
    ]

    operations = [
    ]
