"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '41+q0&=-%76d_@&zf&=g2c8tbp31-fts867t&q#dj^o^o_e(lf'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = True


ALLOWED_HOSTS = ['api.shareorb.com','shareorb-env.eba-zm7j48gb.us-west-1.elasticbeanstalk.com']

# ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS =[
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',




    'allauth.socialaccount',
    'api',
    'allauth',
    'allauth.account',
    'corsheaders',
    'django.contrib.sites',
    'rest_auth',
    'rest_auth.registration',
    'rest_framework',
    'rest_framework.authtoken',
    'userprofile',
    'friends',
    'notification',
    'chat',
    'newChat',
    'mycalendar',
    'mySocialCal',

]

SITE_ID = 1

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'



# Database
# test if commented

# TAKE OUT IF AND ELSE WHEN DEPLOYING

# if 'aaotw5bj0aq6b7.cyxbd89sft5i.us-west-1.rds.amazonaws.com' in os.environ:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ebdb',
        'USER': 'shareorbDB',
        'PASSWORD': 'Pingandy123',
        'HOST': 'aaotw5bj0aq6b7.cyxbd89sft5i.us-west-1.rds.amazonaws.com',
        'PORT': '3306',
    }
}
# else:
#     DATABASES = {
#         'default': {
#                 # 'ENGINE': 'django.db.backends.sqlite3',
#                 # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#
#             'ENGINE': 'django.db.backends.mysql',
#             'NAME': 'test',
#             'USER': 'root',
#             'PASSWORD': 'password',
#             'HOST': '127.0.0.1', # Or an IP Address that your DB is hosted on
#             'PORT': '',
#         },
#     }


# AWS EB Settings
AWS_QUERYSTRING_AUTH = False
AWS_ACCESS_KEY_ID = 'AKIATPBEN3PQCULDTYXA'
AWS_SECRET_ACCESS_KEY = '75YUqArIbGOh/bOzcO45ZmeymSiRB2OV9gll8lXX'

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static")
# STATIC_ROOT = 'static'

STATIC_URL = '/static/'
AUTH_USER_MODEL = "userprofile.User"
ACCOUNT_ADAPTER = 'userprofile.adapters.CustomUserAccountAdapter'
SILENCED_SYSTEM_CHECKS = ['auth.E003', 'auth.W004']
# AUTH_USER_MODEL = 'userprofile.User'
MEDIA_ROOT = os.path.join(BASE_DIR, 'userprofile/media')
# This one is for development
# MEDIA_URL = '/media/'

# Use this one if you want to deploy
AWS_STORAGE_BUCKET_NAME = 'shareorb'
MEDIA_URL = 'http://%s.s3.amazonaws.com/uploads/shareorb/' % AWS_STORAGE_BUCKET_NAME
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

REST_FRAMEWORK = {
        'DEFAULT_PERMISSION_CLASSES': (
            'rest_framework.permissions.IsAuthenticatedOrReadOnly',
            ),
        'DEFAULT_AUTHENTICATION_CLASSES': (
            'rest_framework.authentication.TokenAuthentication',
             'rest_framework.authentication.SessionAuthentication',
             'rest_framework.authentication.BasicAuthentication',

        ),
    }


# pip install django-cors-headers
CORS_ORIGIN_ALLOW_ALL = True

ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_REQUIRED = False

REST_AUTH_REGISTER_SERIALIZERS = {
        'REGISTER_SERIALIZER': 'userprofile.serializers.RegisterSerializer',
}

LOGOUT_ON_PASSWORD_CHANGE = False
OLD_PASSWORD_FIELD_ENABLED = True

ASGI_APPLICATION = 'core.routing.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, 'static')
]
