# Generated by Django 3.0.7 on 2020-09-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeatCondition',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
