# Generated by Django 3.0.7 on 2020-09-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0002_auto_20200917_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='calendar',
            field=models.ManyToManyField(blank=True, to='mycalendar.Calendar'),
        ),
    ]
