# Generated by Django 3.0.7 on 2020-09-26 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycalendar', '0003_auto_20200917_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_host', to=settings.AUTH_USER_MODEL),
        ),
    ]
