# Generated by Django 3.0.7 on 2020-09-26 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycalendar', '0004_auto_20200926_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='accepted',
        ),
        migrations.AddField(
            model_name='event',
            name='accepted',
            field=models.ManyToManyField(related_name='people_accepted', to=settings.AUTH_USER_MODEL),
        ),
    ]
