# Generated by Django 3.0.7 on 2020-10-02 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycalendar', '0005_auto_20200926_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='decline',
            field=models.ManyToManyField(related_name='people_declined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(related_name='people_invited', to=settings.AUTH_USER_MODEL),
        ),
    ]
