# Generated by Django 3.0.7 on 2020-10-03 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycalendar', '0007_auto_20201002_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='accepted',
            field=models.ManyToManyField(related_name='people_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='decline',
            field=models.ManyToManyField(related_name='people_declined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(related_name='people_invited', to=settings.AUTH_USER_MODEL),
        ),
    ]
