# Generated by Django 3.0.7 on 2020-10-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0010_eventmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='backgroundImg',
            field=models.ImageField(blank=True, upload_to='post_pictures/%Y/%m', verbose_name='post_picture'),
        ),
    ]
