# Generated by Django 3.0.3 on 2020-03-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='frontend/public/post_pictures/%Y/%m', verbose_name='post_picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='frontend/public/profile_pictures/%Y/%m', verbose_name='profile_picture'),
        ),
    ]
