# Generated by Django 3.0.7 on 2020-08-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_comment_commentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='PostPic/public/profile_pictures/default.png', upload_to='PostPic/public/profile_pictures/%Y/%m', verbose_name='profile_picture'),
        ),
    ]
