# Generated by Django 3.0.3 on 2020-03-13 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20200313_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='phone_number',
        ),
    ]
