# Generated by Django 3.0.7 on 2020-09-08 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20200824_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_like_condition',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_like_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_people_like',
            field=models.ManyToManyField(blank=True, related_name='commenPeopleList', to=settings.AUTH_USER_MODEL),
        ),
    ]
