# Generated by Django 3.0.7 on 2020-10-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20200908_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='customnotification',
            name='eventId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
