# Generated by Django 3.0.7 on 2020-10-24 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_customnotification_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnotification',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
