# Generated by Django 3.0.7 on 2020-11-25 03:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('userprofile', '0007_auto_20201024_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at', '-updated_at')},
        ),
        migrations.CreateModel(
            name='UserSocialNormPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.PositiveIntegerField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_id', models.PositiveIntegerField()),
                ('owner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_type_post', to='contenttypes.ContentType')),
                ('post_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_type_post', to='contenttypes.ContentType')),
            ],
        ),
    ]
