# Generated by Django 3.0.7 on 2020-11-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20201126_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
