# Generated by Django 3.0.7 on 2020-08-13 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialCalCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialCaldate', models.DateField(auto_now_add=True)),
                ('people_like', models.ManyToManyField(blank=True, related_name='socialLiker', to=settings.AUTH_USER_MODEL)),
                ('socialCalUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_cal_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialCalItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socailItemType', models.CharField(default='post_pic', max_length=30)),
                ('socialItemCaption', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itemImage', models.ImageField(blank=True, upload_to='post_pictures/%Y/%m', verbose_name='post_picture')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_creator', to=settings.AUTH_USER_MODEL)),
                ('itemUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialCalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('content', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_host', to=settings.AUTH_USER_MODEL)),
                ('persons', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialCalComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('calCell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialComments', to='mySocialCal.SocialCalCell')),
                ('commentUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialUserComment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
