# Generated by Django 3.0.7 on 2021-01-12 21:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialCalCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialCaldate', models.DateField(default=django.utils.timezone.now)),
                ('coverPic', models.ImageField(blank=True, upload_to='post_pictures/%Y/%m', verbose_name='post_picture')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dayCaption', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialCalComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialCalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('content', models.TextField(blank=True)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('event_day', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('backgroundImg', models.ImageField(blank=True, upload_to='post_pictures/%Y/%m', verbose_name='post_picture')),
            ],
            options={
                'ordering': ('-event_day', '-start_time'),
            },
        ),
        migrations.CreateModel(
            name='SocialCalItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialItemType', models.CharField(default='picture', max_length=30)),
                ('socialItemCaption', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itemImage', models.ImageField(blank=True, upload_to='post_pictures/%Y/%m', verbose_name='post_picture')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialEventMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('eventObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialEventGroupMessage', to='mySocialCal.SocialCalEvent')),
            ],
        ),
    ]
