# Generated by Django 3.0.7 on 2021-06-16 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialCalCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialCaldate', models.DateField(default=django.utils.timezone.now)),
                ('coverPic', models.ImageField(blank=True, upload_to='post_pictures/%Y/%m', verbose_name='post_picture')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dayCaption', models.TextField(blank=True)),
                ('actionText', models.CharField(default='new', max_length=200)),
                ('people_like', models.ManyToManyField(blank=True, related_name='socialLiker', to=settings.AUTH_USER_MODEL)),
                ('socialCalUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_cal_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialCalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('content', models.TextField(blank=True)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('event_day', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('backgroundImg', models.ImageField(blank=True, upload_to='post_pictures/%Y/%m', verbose_name='post_picture')),
                ('calCell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialEvents', to='mySocialCal.SocialCalCell')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_host', to=settings.AUTH_USER_MODEL)),
                ('inviteList', models.ManyToManyField(related_name='social_invite_list', to=settings.AUTH_USER_MODEL)),
                ('notGoingList', models.ManyToManyField(related_name='social_not_going_list', to=settings.AUTH_USER_MODEL)),
                ('persons', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-event_day', '-start_time'),
            },
        ),
        migrations.CreateModel(
            name='SocialEventMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('eventObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialEventGroupMessage', to='mySocialCal.SocialCalEvent')),
                ('messageUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialEventMessageUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialCellEventPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.PositiveIntegerField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_id', models.PositiveIntegerField()),
                ('owner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_type_social', to='contenttypes.ContentType')),
                ('post_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_type_social', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialCalItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialItemType', models.CharField(default='picture', max_length=30)),
                ('socialItemCaption', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itemImage', models.ImageField(blank=True, upload_to='post_pictures/%Y/%m', verbose_name='post_picture')),
                ('calCell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialPost', to='mySocialCal.SocialCalCell')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_creator', to=settings.AUTH_USER_MODEL)),
                ('itemUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialCalComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comment_like_count', models.IntegerField(blank=True, default=0)),
                ('calCell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialComments', to='mySocialCal.SocialCalCell')),
                ('commentUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialUserComment', to=settings.AUTH_USER_MODEL)),
                ('comment_people_like', models.ManyToManyField(blank=True, related_name='commenPeopleList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
