# Generated by Django 3.0.7 on 2020-08-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySocialCal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialcalitems',
            old_name='socailItemType',
            new_name='socialItemType',
        ),
    ]
