# Generated by Django 3.0.7 on 2020-08-13 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySocialCal', '0002_auto_20200813_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcalevent',
            name='calCell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialEvents', to='mySocialCal.SocialCalCell'),
        ),
        migrations.AddField(
            model_name='socialcalitems',
            name='calCell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialPost', to='mySocialCal.SocialCalCell'),
        ),
    ]
