# Generated by Django 3.0.7 on 2020-08-15 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mySocialCal', '0003_auto_20200813_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcalcell',
            name='testDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
