# Generated by Django 3.0.7 on 2020-08-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySocialCal', '0004_socialcalcell_testdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcalcell',
            name='coverPic',
            field=models.ImageField(blank=True, upload_to='post_pictures/%Y/%m', verbose_name='post_picture'),
        ),
    ]
