# Generated by Django 3.0.7 on 2020-08-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySocialCal', '0005_socialcalcell_coverpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcalcomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
