# Generated by Django 3.0.7 on 2020-08-23 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mySocialCal', '0006_auto_20200820_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcalcell',
            name='socialCaldate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
