# Generated by Django 3.0.7 on 2020-09-02 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mySocialCal', '0007_auto_20200823_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcalevent',
            name='event_day',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='socialcalevent',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='socialcalevent',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
