# Generated by Django 3.0.7 on 2020-10-25 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mySocialCal', '0008_auto_20200902_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcalevent',
            name='backgroundImg',
            field=models.ImageField(blank=True, upload_to='post_pictures/%Y/%m', verbose_name='post_picture'),
        ),
        migrations.CreateModel(
            name='SocialEventMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('eventObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialEventGroupMessage', to='mySocialCal.SocialCalEvent')),
                ('messageUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialEventMessageUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
