# Generated by Django 3.0.7 on 2020-11-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySocialCal', '0009_auto_20201025_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialcalcell',
            name='testDate',
        ),
    ]
