# Generated by Django 3.0.7 on 2020-11-25 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySocialCal', '0010_remove_socialcalcell_testdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialcalevent',
            options={'ordering': ('-event_day', '-start_time')},
        ),
        migrations.AlterModelOptions(
            name='socialcalitems',
            options={'ordering': ['created_at']},
        ),
    ]
