# Generated by Django 3.0.7 on 2020-11-26 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mySocialCal', '0011_auto_20201125_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcalcell',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
