# Generated by Django 3.0.7 on 2021-06-16 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recentMessage', models.TextField(default='Message')),
                ('recentTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('participants', models.ManyToManyField(related_name='chat_parti', to=settings.AUTH_USER_MODEL)),
                ('recentSender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recent_sender', to=settings.AUTH_USER_MODEL)),
                ('seen', models.ManyToManyField(related_name='chat_seen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recentTime'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='text', max_length=30)),
                ('eventTitle', models.CharField(blank=True, max_length=255)),
                ('eventStartTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('eventEndTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('eventPersons', models.IntegerField(blank=True, null=True)),
                ('eventId', models.IntegerField(default=0)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message', to='newChat.Chat')),
                ('messageUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
